vim.api.nvim_set_keymap('t', '<Esc>', '<C-\\><C-n>', { noremap = true })
vim.api.nvim_set_keymap('n', '<leader>e', ':Explore<CR>', { noremap= true})
vim.api.nvim_set_keymap('n', '<leader>ve', ':Vexplore<CR>', { noremap= true})
vim.api.nvim_set_keymap('n', '<leader>s', ':split<CR>', { noremap= true})
vim.api.nvim_set_keymap('n', '<leader>vs', ':vsplit<CR>', { noremap= true})
vim.api.nvim_set_keymap('x', '<leader>p', '\"_dP', { noremap= true})
