#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#YABAI STUFF

#yabai -m config layout bsp

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app=".*" layer=normal
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Finder$" manage=off sticky=on
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Telegram$" manage=off sticky=on
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="WhatsApp" manage=off
yabai -m rule --add app="^VIA$" manage=off
yabai -m rule --add app="^TinkerTool$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Home Assistant$" manage=off
yabai -m rule --add title="^Steam$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Archetype" manage=off
yabai -m rule --add app="^Riot Client$" manage=off
yabai -m rule --add app="^League of Legends$" manage=off
yabai -m rule --add app="^VLC" manage=off
yabai -m rule --add app="^Cisco Secure Client" manage=off

# Some random global settings
#yabai -m config focus_follows_mouse          autoraise
#yabai -m config focus_follows_mouse          on
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_shadow off

# yabai -m config window_border on
# yabai -m config window_border_blur off
# yabai -m config window_border_radius 11
# yabai -m config window_border_width 2
# yabai -m config active_window_border_color 
# yabai -m config normal_window_border_color 
yabai -m config window_opacity off
yabai -m config normal_window_opacity 0.8

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus first"
yabai -m signal --add event=window_minimized action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus first"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus first"
yabai -m signal --add event=space_changed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus first"

borders active_color=0xFFbd93f9 inactive_color=0x00FFFFFF width=4.0 style="round" 2>/dev/null 1>&2 &

echo "yabai configuration loaded.."
