#!/usr/bin/env sh

#YABAI STUFF

#yabai -m config layout bsp

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --apply

appsToIgnore=(
    "System Settings"
    "Karabiner-Elements"
    "Karabiner-EventViewer"
    "Disk Utility"
    "System Information"
    "Activity Monitor"
    "Spotify"
    "Stats"
    "zoom.us"
    "VIA"
    "TinkerTool"
    "Discord"
    "App Store"
    "Home Assistant"
    "Calculator"
    "Archetype"
    "Riot Client"
    "League of Legends"
    "VLC"
    "Cisco Secure Client"
    "Numi"
    "Calendar"
    "Prism Launcher"
    "iPhone Mirroring"
    "FaceTime"
    "Notes"
    "ChatGPT"
    "TrackWeight"
    "BetterDisplay"
    "AlDente"
    "TextEdit"
    "Raycast"
    "Gemini"
    "OpenClaw"
)

for item in "${appsToIgnore[@]}"; do
    yabai -m rule --add app="^$item$" manage=off
done
yabai -m rule --add app="WhatsApp" manage=off
yabai -m rule --add title="^Steam$" manage=off
yabai -m rule --add app="Zen" title="Picture-in-Picture" manage=off
yabai -m rule --add app="Finder" sticky=on manage=off
yabai -m rule --add app="Telegram" sticky=on manage=off
 
# Some random global settings
#yabai -m config mouse_follows_focus on
# New window spawns to the right if vertical split, or bottom if horizontal split

# yabai -m config window_border on
# yabai -m config window_border_blur off
# yabai -m config window_border_radius 11
# yabai -m config window_border_width 2
# yabai -m config active_window_border_color 
# yabai -m config normal_window_border_color 
yabai -m config window_opacity off
yabai -m config normal_window_opacity 0.8

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus first"
yabai -m signal --add event=window_minimized action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus first"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus first"
yabai -m signal --add event=space_changed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus first"

borders active_color=0xFFc9a8fa inactive_color=0x00FFFFFF width=1.5 style="round" order="above" hidpi="on"

echo "yabai configuration loaded.."
